# conda environment file for tilezilla
name: tilezilla
channels:
    # they nicely build rasterio for us
    - conda-forge
dependencies:
    # base
    - numpy>=1.10.0
    # geographic data packages
    - rasterio>=0.31.0
    - gdal
    - shapely>=1.5.13
    - netcdf4
    # database
    - sqlalchemy
    # config file
    - pyyaml>=3.11
    - jsonschema>=2.4.0
    # metadata parsing
    - beautifulsoup4
    - lxml
    # plotting
    - matplotlib>=1.5.1
    # Required for "clover" -- see below
    # - pillow (jpeg8 dependency conflicts with gdal/rasterio jpeg9)
    - fiona
    # Required but missing from conda
    - pip:
        # better datetime
        - arrow>=0.7.0
        # cli
        - click>=6.0
        - click_plugins>=1.0
        # database utils
        - sqlalchemy-utils
        # compatibility with Python2
        - pathlib>=1.0.1
        - six>=1.10.0
        # clover -- used for CRS translation "NetCDF CF" <-> "GDAL/Proj4"
        - git+git://github.com/consbio/clover.git
