# conda environment file for tilezilla
name: tilezilla
channels:
    # they nicely build rasterio for us
    - ioos
dependencies:
    # base
    - numpy>=1.10.0
    # geographic data packages
    - rasterio>=0.31.0
    - gdal
    - libgdal
    - shapely>=1.5.13
    # database
    - sqlalchemy
    # config file
    - pyyaml>=3.11
    # metadata parsing
    - beautifulsoup4
    # plotting
    - matplotlib>=1.5.1
    # Required but missing from conda
    - pip:
        # better datetime
        - arrow>=0.7.0
        # cli
        - click>=6.0
        - click_plugins>=1.0
        # database utils
        - sqlalchemy-utils
        # compatibility with Python2
        - pathlib>=1.0.1
        - six==1.10.0
        # TODO: remove temp workaround for missing libcom_err.so
        - rasterio>=0.31
